version: '3'

volumes:
  pg_data_kittygram:
  static_kittygram:
  media_kittygram:
services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_kittygram:/var/lib/postgresql/data
  backend:
    image: norugin/kittygram_backend
    environment:
      ALLOWED_HOSTS: "84.252.138.112,kittynorugin.duckdns.org,127.0.0.1,localhost"
    env_file: .env
    volumes:
      - static_kittygram:/backend_static
      - media_kittygram:/app/media
    depends_on:
      - db

  frontend:
    image: norugin/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_kittygram:/frontend_static
  gateway:
    image: norugin/kittygram_gateway
    env_file: .env
    volumes:
      - static_kittygram:/static/
      - media_kittygram:/media
    ports:
      - 9000:80
